network_type: Test

bitshares:
    # irreversible, or head
    watch_mode: irreversible
        
    connection:
        Main:
         blocking: True
         node:
            - wss://eu.nodes.bitshares.works
            - wss://sg.nodes.bitshares.works
            - wss://us.nodes.bitshares.works 
        
        Test:
         blocking: True
         node:
            - wss://node.testnet.bitshares.eu

    assets:
        - asset_id: 1.3.0
          address: None
          name: BTS
          accuracy: 5
        - asset_id: 1.3.121
          address: None
          name: USD
          accuracy: 4        
        - asset_id: 1.3.120
          address: None
          name: EUR
          accuracy: 4