bitshares:
    exchange_account_name: lykke-test
    exchange_account_id: 1.2.20137
    
    assets:
        - asset_id: 1.3.0
          address: None
          name: BTS
          accuracy: 5
        - asset_id: 1.3.121
          address: None
          name: USD
          accuracy: 4        
        - asset_id: 1.3.120
          address: None
          name: EUR
          accuracy: 4
          
    transaction_expiration_in_sec: 43200