network_type: Test

bitshares:
    # irreversible, or head
    watch_mode: irreversible
        
    connection:
        Main:
         blocking: True
         node:
            - wss://eu.nodes.bitshares.works
            - wss://sg.nodes.bitshares.works
            - wss://us.nodes.bitshares.works 
        
        Test:
         blocking: True
         node:
            - wss://node.testnet.bitshares.eu
