operation_storage:
 retry_policy:
  num: 3
  wait_in_ms: 0
 use: azuretest
 mongodb:
     seeds: 
         - localhost:27017
     db: bitshares-operation-storage
     operation_collection: operations
     status_collection: status
     address_collection: address
 mongodbtest:
     seeds: 
         - localhost:27017
     db: bitshares-operation-storage
     operation_collection: operations_test
     status_collection: status_test
     address_collection: address_test
 azure:
    account: lkedevbcnbitshares
    key: # insert key
    db: lykkebitsharesoperationstorage
    operation_table: operations
    status_table: status
    address_table: address
 azuretest:
    account: lkedevbcnbitshares
    key: # insert key
    db: lykkebitsharesoperationstorage
    operation_table: operationstest
    status_table: statustest
    address_table: addresstest