# must have correponding entry in bitshares/chains
network_type: Test

log_folder: dump/logs

wsgi:
 name: bexi
 version: 0.0.1
 host: localhost
 port: 5000
 
operation_storage:
 use: azuretest
 mongodb:
     seeds: 
         - localhost:27017
     db: bitshares-operation-storage
     operation_collection: operations
     status_collection: status
     address_collection: address
 mongodbtest:
     seeds: 
         - localhost:27017
     db: bitshares-operation-storage
     operation_collection: operations_test
     status_collection: status_test
     address_collection: address_test
 azure:
    account: null # insert azure account
    key: null # insert azure key
    db: lykkebitsharesoperationstorage
    operation_table: operations
    status_table: status
    address_table: address
 azuretest:
    account: null # insert azure account
    key: null # insert azure key
    db: lykkebitsharesoperationstorage
    operation_table: operationstest
    status_table: statustest
    address_table: addresstest
    
bitshares:
    exchange_account_name: null # insert bitshares account name
    exchange_account_id: null # insert bitshares account id
    exchange_account_active_key: null # insert active key of exchange account
    
    # irreversible, or head
    watch_mode: irreversible
        
    connection:
        Main:
         node:
            - wss://eu.nodes.bitshares.works
            - wss://sg.nodes.bitshares.works
            - wss://us.nodes.bitshares.works 
        
        Test:
         node:
            - wss://node.testnet.bitshares.eu
         keys:
            - null # insert active key of exchange account
    
    assets:
        - asset_id: 1.3.0
          address: None
          name: BTS
          accuracy: 5
        - asset_id: 1.3.121
          address: None
          name: USD
          accuracy: 4        
        - asset_id: 1.3.120
          address: None
          name: EUR
          accuracy: 4
